### ISSUE TITLE
PyPI packaging

### ISSUE THREAD

**Issue by GijsTimmers** [Dirble/streamscrobbler-python#5]
Hi,

I'm considering using `streamscrobbler-python` in my own project, called [`yamlradio`](https://github.com/GijsTimmers/yamlradio). To make the install for end users as easy as possible, I'd like to have a PyPI package for it, so everything can be installed via `pip`. Can you make such a package? I can do it for you as well, if you want to.

**Comment by confact** [comment]
Hi @GijsTimmers - I would accept a pull-request for that.

**Comment by GijsTimmers** [comment]
alright, please take a look at https://github.com/Dirble/streamscrobbler-python/pull/7
